# Generated by Django 5.0.1 on 2024-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
